/**
 * Canonical 12 Swarasthanas of Indian Classical Music (Hindustani & Carnatic)
 * Indexed by semitone (0 to 11) and cent offset from Shadja (Sa = 0 cents).
 */
export const SWARA_TABLE = [
  { index: 0, id: 'S', hindustani: 'Shadja (Sa)', carnatic: 'Shadjam (Sa)', cents: 0, short: 'Sa', variant: 'achala' },
  { index: 1, id: 'r1', hindustani: 'Komal Rishabh (re)', carnatic: 'Shuddha Rishabham (R1)', cents: 100, short: 're', variant: 'komal' },
  { index: 2, id: 'R2', hindustani: 'Shuddha Rishabh (Re)', carnatic: 'Chatushruti Rishabham (R2)', cents: 200, short: 'Re', variant: 'shuddha' },
  { index: 3, id: 'g2', hindustani: 'Komal Gandhar (ga)', carnatic: 'Sadharana Gandharam (G2)', cents: 300, short: 'ga', variant: 'komal' },
  { index: 4, id: 'G3', hindustani: 'Shuddha Gandhar (Ga)', carnatic: 'Antara Gandharam (G3)', cents: 400, short: 'Ga', variant: 'shuddha' },
  { index: 5, id: 'M1', hindustani: 'Shuddha Madhyam (Ma)', carnatic: 'Shuddha Madhyamam (M1)', cents: 500, short: 'Ma', variant: 'shuddha' },
  { index: 6, id: 'M2', hindustani: 'Teevra Madhyam (Ma#)', carnatic: 'Prati Madhyamam (M2)', cents: 600, short: 'Ma#', variant: 'teevra' },
  { index: 7, id: 'P', hindustani: 'Pancham (Pa)', carnatic: 'Panchamam (Pa)', cents: 700, short: 'Pa', variant: 'achala' },
  { index: 8, id: 'd1', hindustani: 'Komal Dhaivat (dha)', carnatic: 'Shuddha Dhaivatam (D1)', cents: 800, short: 'dha', variant: 'komal' },
  { index: 9, id: 'D2', hindustani: 'Shuddha Dhaivat (Dha)', carnatic: 'Chatushruti Dhaivatam (D2)', cents: 900, short: 'Dha', variant: 'shuddha' },
  { index: 10, id: 'n2', hindustani: 'Komal Nishad (ni)', carnatic: 'Kaisiki Nishadam (N2)', cents: 1000, short: 'ni', variant: 'komal' },
  { index: 11, id: 'N3', hindustani: 'Shuddha Nishad (Ni)', carnatic: 'Kakali Nishadam (N3)', cents: 1100, short: 'Ni', variant: 'shuddha' }
];

export const THAAT_FAMILIES = {
  Kalyan: 'All shuddha swaras except Teevra Madhyam (M2): S R2 G3 M2 P D2 N3',
  Bilawal: 'All shuddha swaras (major diatonic equivalent): S R2 G3 M1 P D2 N3',
  Khamaj: 'Komal Nishad (n2) in descent with Shuddha Nishad (N3) in ascent: S R2 G3 M1 P D2 n2/N3',
  Bhairav: 'Komal Rishabh (r1) and Komal Dhaivat (d1) with Shuddha Gandhar (G3) and Shuddha Nishad (N3): S r1 G3 M1 P d1 N3',
  Poorvi: 'Komal Rishabh (r1), Komal Dhaivat (d1), and Teevra Madhyam (M2): S r1 G3 M2 P d1 N3',
  Kafi: 'Komal Gandhar (g2) and Komal Nishad (n2) with Shuddha Re and Dha: S R2 g2 M1 P D2 n2',
  Asavari: 'Komal Gandhar (g2), Komal Dhaivat (d1), and Komal Nishad (n2): S R2 g2 M1 P d1 n2',
  Bhairavi: 'All four komal swaras (r1, g2, d1, n2) with Shuddha Madhyam (M1): S r1 g2 M1 P d1 n2',
  Todi: 'Komal Rishabh (r1), Komal Gandhar (g2), Teevra Madhyam (M2), Komal Dhaivat (d1), Shuddha Nishad (N3): S r1 g2 M2 P d1 N3'
};

export const RAGA_CATALOG = [
  {
    id: 'yaman',
    name: 'Raga Yaman',
    carnaticEquivalent: 'Mechakalyani (Melakarta 65)',
    tradition: 'Hindustani & Carnatic Dual',
    thaat: 'Kalyan',
    jati: 'Sampurna-Sampurna (7 notes)',
    swaras: ['S', 'R2', 'G3', 'M2', 'P', 'D2', 'N3'],
    varjya: ['r1', 'g2', 'M1', 'd1', 'n2'],
    aroha: 'N3 R2 G3 M2 D2 N3 S',
    avaroha: 'S N3 D2 P M2 G3 R2 S',
    pakad: 'N3 R2 G3, R2 G3 M2 P, M2 D2 N3 S, P R2 G3 R2 S',
    pakadNgrams: ['N3 R2 G3', 'R2 G3 M2', 'G3 M2 P', 'M2 P D2', 'P D2 N3', 'M2 D2 N3', 'P R2 G3', 'G3 R2 S'],
    vadi: 'G3',
    samvadi: 'N3',
    nyasa: ['G3', 'R2', 'N3', 'P'],
    prahar: 'Early Night (1st Prahar of Night, 6 PM – 9 PM)',
    praharKey: 'early_night',
    rasa: 'Shringara & Bhakti — serene, auspicious, luminous evening devotion',
    gamakaProfile: 'Meend glides from P to R2 (P->R2->G3) and lower-octave N3 entry avoiding direct S in ascent',
    sampleFile: '/samples/raga-yaman.mp3',
    youtubeUrl: 'https://www.youtube.com/watch?v=x9DKjCxzDQg',
    vocalSource: 'Human Vocal (C# / Kali Ek) — Aroh, Avroh & Pakad (0:15–0:40)'
  },
  {
    id: 'bhairav',
    name: 'Raga Bhairav',
    carnaticEquivalent: 'Mayamalavagowla (Melakarta 15)',
    tradition: 'Hindustani & Carnatic Dual',
    thaat: 'Bhairav',
    jati: 'Sampurna-Sampurna (7 notes)',
    swaras: ['S', 'r1', 'G3', 'M1', 'P', 'd1', 'N3'],
    varjya: ['R2', 'g2', 'M2', 'D2', 'n2'],
    aroha: 'S r1 G3 M1 P d1 N3 S',
    avaroha: 'S N3 d1 P M1 G3 r1 S',
    pakad: 'G3 M1 d1 d1 P, G3 M1 r1 r1 S, N3 S r1 S',
    pakadNgrams: ['S r1 G3', 'r1 G3 M1', 'G3 M1 P', 'M1 P d1', 'P d1 N3', 'd1 P M1', 'P M1 G3', 'M1 G3 r1', 'G3 r1 S', 'G3 M1 d1', 'M1 d1 P'],
    vadi: 'd1',
    samvadi: 'r1',
    nyasa: ['r1', 'd1', 'M1', 'P'],
    prahar: 'Dawn / Early Morning Sandhiprakash (5 AM – 8 AM)',
    praharKey: 'dawn_sandhiprakash',
    rasa: 'Gambhir, Shanta & Adbhuta — solemn, awe-inspiring, meditative awakening',
    gamakaProfile: 'Signature slow symmetrical Andolan (microtonal oscillation) on Komal Dha (d1) and Komal Re (r1)',
    sampleFile: '/samples/raga-bhairav.mp3',
    youtubeUrl: 'https://www.youtube.com/watch?v=TSF6FihBCaQ',
    vocalSource: 'Human Vocal (G# / Kali Char) — Aroh & Avroh (0:00–0:28)'
  },
  {
    id: 'bhupali',
    name: 'Raga Bhupali',
    carnaticEquivalent: 'Mohanam (Janya of Harikambhoji / Kalyani)',
    tradition: 'Hindustani & Carnatic Dual',
    thaat: 'Kalyan',
    jati: 'Audava-Audava (5-note Pentatonic)',
    swaras: ['S', 'R2', 'G3', 'P', 'D2'],
    varjya: ['r1', 'g2', 'M1', 'M2', 'd1', 'n2', 'N3'],
    aroha: 'S R2 G3 P D2 S',
    avaroha: 'S D2 P G3 R2 S',
    pakad: 'G3 R2 S D2, S R2 G3, P G3 D2 P G3 R2 S',
    pakadNgrams: ['S R2 G3', 'R2 G3 P', 'G3 P D2', 'P D2 S', 'S D2 P', 'D2 P G3', 'P G3 R2', 'G3 R2 S'],
    vadi: 'G3',
    samvadi: 'D2',
    nyasa: ['G3', 'R2', 'P', 'S'],
    prahar: 'Early Night (1st Prahar of Night, 6 PM – 9 PM)',
    praharKey: 'early_night',
    rasa: 'Shanta & Prasanna — tranquil, pure, expansive pentatonic clarity',
    gamakaProfile: 'Clean pentatonic glides (Meend from D2 to G3 and P to G3); strictly omits both Madhyam and Nishad',
    sampleFile: '/samples/raga-bhupali.mp3',
    youtubeUrl: 'https://www.youtube.com/watch?v=D4jFaFDHa5g',
    vocalSource: 'Human Vocal (B) — Aaroh, Avroh & Pakad (0:16–0:43)'
  },
  {
    id: 'malkauns',
    name: 'Raga Malkauns',
    carnaticEquivalent: 'Hindolam (Janya of Natabhairavi)',
    tradition: 'Hindustani & Carnatic Dual',
    thaat: 'Bhairavi',
    jati: 'Audava-Audava (5-note Pentatonic)',
    swaras: ['S', 'g2', 'M1', 'd1', 'n2'],
    varjya: ['r1', 'R2', 'G3', 'M2', 'P', 'D2', 'N3'],
    aroha: 'n2 S g2 M1 d1 n2 S',
    avaroha: 'S n2 d1 M1 g2 M1 g2 S',
    pakad: 'M1 g2 M1 d1 n2 d1, M1 g2 S',
    pakadNgrams: ['S g2 M1', 'g2 M1 d1', 'M1 d1 n2', 'd1 n2 S', 'S n2 d1', 'n2 d1 M1', 'd1 M1 g2', 'M1 g2 S'],
    vadi: 'M1',
    samvadi: 'S',
    nyasa: ['M1', 'g2', 'd1', 'S'],
    prahar: 'Late Night / Midnight (3rd Prahar of Night, 12 AM – 3 AM)',
    praharKey: 'late_night',
    rasa: 'Veera & Gambhir — deep, mystical, fearless midnight introspection',
    gamakaProfile: 'Slow heavy Meend and oscillation on g2, M1, and d1; completely omits Re and Pa (Madhyam acts as central pivot)',
    sampleFile: '/samples/raga-malkauns.mp3',
    youtubeUrl: 'https://www.youtube.com/watch?v=skkrjRDcwXw',
    vocalSource: 'Human Vocal (C / Safed Ek) — Aroh, Avroh & Pakad (0:00–0:28)'
  },
  {
    id: 'darbari_kanada',
    name: 'Raga Darbari Kanada',
    carnaticEquivalent: 'Darbari Kanada (Adopted in Carnatic)',
    tradition: 'Hindustani Classical',
    thaat: 'Asavari',
    jati: 'Sampurna-Sampurna Vakra (7 notes)',
    swaras: ['S', 'R2', 'g2', 'M1', 'P', 'd1', 'n2'],
    varjya: ['r1', 'G3', 'M2', 'D2', 'N3'],
    aroha: 'S R2 g2 M1 P d1 n2 S',
    avaroha: 'S d1 n2 P, M1 P g2 M1 R2 S',
    pakad: 'R2 g2 R2 S, d1 n2 P, M1 P g2 M1 R2 S',
    pakadNgrams: ['S R2 g2', 'R2 g2 M1', 'R2 g2 R2', 'd1 n2 P', 'g2 M1 R2', 'M1 R2 S', 'n2 P M1', 'P g2 M1'],
    vadi: 'R2',
    samvadi: 'P',
    nyasa: ['R2', 'P', 'S'],
    prahar: 'Late Night / Midnight (3rd Prahar of Night, 11 PM – 2 AM)',
    praharKey: 'late_night',
    rasa: 'Karuna & Gambhir — regal, majestic, deeply contemplative courtly gravity',
    gamakaProfile: 'Wide, slow horizontal Andolan on Komal Gandhar (g2) and Komal Dhaivat (d1), plus Vakra phrase g2-M1-R2-S and d1-n2-P',
    sampleFile: '/samples/raga-darbari-kanada.mp3',
    youtubeUrl: 'https://www.youtube.com/watch?v=TxORN-ZnBY4',
    vocalSource: 'Human Vocal (C / Safed Ek) — Aroh, Avroh & Pakar (0:32–1:00)'
  },
  {
    id: 'hamsadhwani',
    name: 'Raga Hamsadhwani',
    carnaticEquivalent: 'Hamsadhwani (Created by Ramaswami Dikshitar)',
    tradition: 'Carnatic & Hindustani Dual',
    thaat: 'Bilawal',
    jati: 'Audava-Audava (5-note Pentatonic)',
    swaras: ['S', 'R2', 'G3', 'P', 'N3'],
    varjya: ['r1', 'g2', 'M1', 'M2', 'd1', 'D2', 'n2'],
    aroha: 'S R2 G3 P N3 S',
    avaroha: 'S N3 P G3 R2 S',
    pakad: 'G3 P N3 P G3 R2, G3 R2 N3 P S',
    pakadNgrams: ['S R2 G3', 'R2 G3 P', 'G3 P N3', 'P N3 S', 'S N3 P', 'N3 P G3', 'P G3 R2', 'G3 R2 S'],
    vadi: 'R2',
    samvadi: 'P',
    nyasa: ['R2', 'G3', 'P', 'S'],
    prahar: 'Early Evening / Auspicious Concert Opener (6 PM – 9 PM)',
    praharKey: 'early_night',
    rasa: 'Utsaha & Mangala — bright, celebratory, crisp and uplifting',
    gamakaProfile: 'Sparkling Kampita and Sphurita ornamentations on R2, G3, and N3; strictly omits Madhyam and Dhaivat',
    sampleFile: '/samples/raga-hamsadhwani.mp3',
    youtubeUrl: 'https://www.youtube.com/watch?v=AgCar9hWWas',
    vocalSource: 'Human Vocal (G / Pancham) — Moorchana & Alapana (0:24–0:49)'
  },
  {
    id: 'bhimpalasi',
    name: 'Raga Bhimpalasi',
    carnaticEquivalent: 'Abheri / Karnataka Devagandhari',
    tradition: 'Hindustani & Carnatic Dual',
    thaat: 'Kafi',
    jati: 'Audava-Sampurna (5 up, 7 down)',
    swaras: ['S', 'R2', 'g2', 'M1', 'P', 'D2', 'n2'],
    varjya: ['r1', 'G3', 'M2', 'd1', 'N3'],
    aroha: 'n2 S g2 M1 P n2 S',
    avaroha: 'S n2 D2 P M1 g2 R2 S',
    pakad: 'n2 S M1, M1 g2 P M1, g2 M1 g2 R2 S',
    pakadNgrams: ['n2 S g2', 'g2 M1 P', 'P M1 g2', 'M1 g2 R2', 'g2 R2 S'],
    vadi: 'M1',
    samvadi: 'S',
    nyasa: ['M1', 'P', 'g2', 'S'],
    prahar: 'Late Afternoon (3rd Prahar of Day, 1 PM – 4 PM)',
    praharKey: 'afternoon',
    rasa: 'Shringara & Viraha — tender, yearning afternoon warmth',
    gamakaProfile: 'Omits Re and Dha in Aroha (ascending n2-S-g2-M1-P-n2-S) while touching D2 and R2 in Avaroha descent with Meend from P to g2',
    sampleFile: null
  },
  {
    id: 'todi',
    name: 'Raga Miyan ki Todi',
    carnaticEquivalent: 'Shubhapantuvarali (Melakarta 45)',
    tradition: 'Hindustani Classical',
    thaat: 'Todi',
    jati: 'Sampurna-Sampurna (7 notes)',
    swaras: ['S', 'r1', 'g2', 'M2', 'P', 'd1', 'N3'],
    varjya: ['R2', 'G3', 'M1', 'D2', 'n2'],
    aroha: 'S r1 g2 M2 P d1 N3 S',
    avaroha: 'S N3 d1 P M2 g2 r1 S',
    pakad: 'd1 P M2 g2 r1 g2 r1 S, r1 g2 M2 d1 N3 S',
    pakadNgrams: ['r1 g2 M2', 'M2 d1 N3', 'M2 g2 r1', 'g2 r1 S', 'd1 P M2'],
    vadi: 'd1',
    samvadi: 'g2',
    nyasa: ['g2', 'r1', 'd1', 'S'],
    prahar: 'Late Morning (2nd Prahar of Day, 9 AM – 12 PM)',
    praharKey: 'late_morning',
    rasa: 'Karuna & Bhakti — poignant, prayerful, intensely expressive humility',
    gamakaProfile: 'Delicate microtonal oscillation on Komal Ga (g2) and Komal Re (r1) paired with Teevra Madhyam (M2)',
    sampleFile: null
  },
  {
    id: 'bhairavi',
    name: 'Raga Bhairavi',
    carnaticEquivalent: 'Hanumatodi (Melakarta 8) / Sindhubhairavi',
    tradition: 'Hindustani & Carnatic Dual',
    thaat: 'Bhairavi',
    jati: 'Sampurna-Sampurna (7 notes)',
    swaras: ['S', 'r1', 'g2', 'M1', 'P', 'd1', 'n2'],
    varjya: ['R2', 'G3', 'M2', 'D2', 'N3'],
    aroha: 'S r1 g2 M1 P d1 n2 S',
    avaroha: 'S n2 d1 P M1 g2 r1 S',
    pakad: 'M1 g2 r1 S, d1 n2 S r1 g2 M1 P',
    pakadNgrams: ['S r1 g2', 'r1 g2 M1', 'M1 g2 r1', 'g2 r1 S', 'P d1 n2'],
    vadi: 'M1',
    samvadi: 'S',
    nyasa: ['M1', 'P', 'r1', 'S'],
    prahar: 'Morning / Concert Finale (Sarva-Kaalik)',
    praharKey: 'dawn_sandhiprakash',
    rasa: 'Bhakti & Karuna — sweet, soulful, devotional culmination',
    gamakaProfile: 'All four komal swaras (r1, g2, d1, n2) with fluid slides across r1-g2-M1 and d1-n2-S',
    sampleFile: null
  },
  {
    id: 'puriya_dhanashri',
    name: 'Raga Puriya Dhanashri',
    carnaticEquivalent: 'Kamavardhini / Pantuvarali (Melakarta 51)',
    tradition: 'Hindustani & Carnatic Dual',
    thaat: 'Poorvi',
    jati: 'Sampurna-Sampurna (7 notes)',
    swaras: ['S', 'r1', 'G3', 'M2', 'P', 'd1', 'N3'],
    varjya: ['R2', 'g2', 'M1', 'D2', 'n2'],
    aroha: 'N3 r1 G3 M2 P d1 N3 S',
    avaroha: 'S N3 d1 P M2 G3 M2 r1 G3 r1 S',
    pakad: 'N3 r1 G3, M2 r1 G3, M2 d1 N3 d1 P, M2 G3 M2 r1 G3 r1 S',
    pakadNgrams: ['N3 r1 G3', 'M2 r1 G3', 'M2 d1 N3', 'd1 P M2', 'G3 r1 S'],
    vadi: 'P',
    samvadi: 'r1',
    nyasa: ['P', 'G3', 'r1', 'S'],
    prahar: 'Dusk / Sunset Sandhiprakash (5 PM – 7 PM)',
    praharKey: 'dusk_sandhiprakash',
    rasa: 'Gambhir & Vairagya — twilight intensity, golden dusk reflection',
    gamakaProfile: 'Chromatic tension between r1, G3, M2, and d1 with signature M2-G3-M2-r1-G3-r1-S cadence',
    sampleFile: null
  },
  {
    id: 'desh',
    name: 'Raga Desh',
    carnaticEquivalent: 'Desh / Kedaram-family Janya',
    tradition: 'Hindustani Classical',
    thaat: 'Khamaj',
    jati: 'Audava-Sampurna (5 up, 7 down)',
    swaras: ['S', 'R2', 'G3', 'M1', 'P', 'D2', 'n2', 'N3'],
    varjya: ['r1', 'g2', 'M2', 'd1'],
    aroha: 'S R2 M1 P N3 S',
    avaroha: 'S n2 D2 P M1 G3 R2 G3 N3 S',
    pakad: 'R2 M1 P N3 S, R2 n2 D2 P, M1 G3 R2 G3 N3 S',
    pakadNgrams: ['R2 M1 P', 'M1 P N3', 'n2 D2 P', 'M1 G3 R2', 'R2 G3 N3'],
    vadi: 'R2',
    samvadi: 'P',
    nyasa: ['R2', 'P', 'N3', 'S'],
    prahar: 'Late Evening / Night (2nd Prahar of Night, 9 PM – 12 AM)',
    praharKey: 'early_night',
    rasa: 'Shringara & Utsaha — romantic, lyrical, monsoon breeze',
    gamakaProfile: 'Uses Shuddha Nishad (N3) in ascending R2-M1-P-N3-S and Komal Nishad (n2) in descending S-n2-D2-P-M1-G3-R2',
    sampleFile: null
  },
  {
    id: 'bageshri',
    name: 'Raga Bageshri',
    carnaticEquivalent: 'Sriranjani (Janya of Kharaharapriya)',
    tradition: 'Hindustani & Carnatic Dual',
    thaat: 'Kafi',
    jati: 'Audava-Sampurna (5/6 up, 7 down)',
    swaras: ['S', 'R2', 'g2', 'M1', 'P', 'D2', 'n2'],
    varjya: ['r1', 'G3', 'M2', 'd1', 'N3'],
    aroha: 'n2 S g2 M1 D2 n2 S',
    avaroha: 'S n2 D2 M1 P D2 g2 M1 g2 R2 S',
    pakad: 'D2 n2 S, M1 D2 n2 D2, M1 P D2 g2 M1 g2 R2 S',
    pakadNgrams: ['g2 M1 D2', 'M1 D2 n2', 'M1 P D2', 'D2 g2 M1', 'g2 R2 S'],
    vadi: 'M1',
    samvadi: 'S',
    nyasa: ['M1', 'D2', 'g2', 'S'],
    prahar: 'Midnight (2nd/3rd Prahar of Night, 10 PM – 1 AM)',
    praharKey: 'late_night',
    rasa: 'Shringara & Karuna — intimate, nocturnal longing and poise',
    gamakaProfile: 'Skips Pa in ascent (g2-M1-D2-n2-S) and introduces Pa in Vakra descent (M1-P-D2-g2-M1-g2-R2-S)',
    sampleFile: null
  }
];

export function getRagaById(id) {
  return RAGA_CATALOG.find(r => r.id === id) || null;
}
